version: "3"

services:
  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb-local
    volumes:
      - ./docker/influxdb2/data:/var/lib/influxdb2
      - ./docker/influxdb2/config:/etc/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=organization
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana-local
    ports:
      - 8085:3000
    depends_on:
      - influxdb
    volumes:
     - 'grafana_storage:/var/lib/grafana'
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:8085

volumes:
  grafana_storage: {}